Hazim/feature/right sidebar
hicsail/fhs-online-inquiry-system-frontend pull request #24
Opened 2023-09-27 20:45 UTC by ZimLim

# Description

> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- Added right sidebar with filters and description
- Ability to add new filters from sidebar
- Added autocomplete
## Checklist

- [ ] This PR can be reviewed in under 30 minutes
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned reviewers to this PR.

2023-09-28 15:34 UTC, wenhwang97 reviewed
I highlighted the `<Autocomplete>` issue. Surprised that it wasn't discovered at that time. Probably need to create a separate PR just to fix this issue.

2023-09-28 15:34 UTC, wenhwang97 commented on src/pages/Dashboard.tsx
>                />
Something went wrong here. `<Autocomplete>` is not doing its job. When you are typing in the textfield, the dropdown never changes. I did a quick investigation and the issue happened here #21 .

2023-09-28 15:36 UTC, wenhwang97 requested changes
Look very nice! Just some nitpicks. Make sure to run prettier to clean up the code formatting.

2023-09-28 15:36 UTC, wenhwang97 commented on src/pages/Dashboard.tsx
> +    console.log(newValue)
Remove this printing statement

2023-09-28 15:38 UTC, ZimLim commented on src/pages/Dashboard.tsx
>                />
I didn't particularly pay attention to it but I can make the fix separately

2023-09-28 16:55 UTC, wenhwang97 requested changes
Need to run `npm run prettier:fix` to fix the formatting

2023-09-29 14:46 UTC, wenhwang97 approved these changes

2023-10-02 15:35 UTC, merged