Slider
hicsail/fhs-online-inquiry-system-frontend pull request #4
Opened 2023-07-05 16:39 UTC by ckarjadi

# Description

A very simple implementation of a Slider that drops two sliders into the main page. The slider code was taken from https://mui.com/material-ui/react-slider/ and https://codesandbox.io/s/cl9qdd?file=/index.tsx.

> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Checklist

- [ ] This PR can be reviewed in under 30 minutes
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have assigned reviewers to this PR.

2023-07-05 18:23 UTC, wenhwang97 requested changes

2023-07-05 18:23 UTC, wenhwang97 commented on src/r_slider.tsx
We want to keep the naming convention consistent, so here we may use camel case for all names.

2023-07-05 18:23 UTC, wenhwang97 commented on src/r_slider.tsx
The slider is good. I also would like you to implement other parts for the filter. I have attached an image to your card on Clickup. That is how it should look like. I also added a few checklist items in your card. Let me know if there are anything that is unclear or does not make sense.

2023-07-11 19:47 UTC, ckarjadi commented on src/r_slider.tsx
Ok - renaming to DemoSlider in the next commit, for now.

2023-07-11 19:49 UTC, ckarjadi commented on src/r_slider.tsx
Sounds good - the next commit will include the start/end ranges (although we may want to go over 100, since we may have participants who are older than 100 in rare cases) and the value of the start/end of the age ranges is also always visible. 

I also will change the minimum distance between the start/end to 0 for now (was 10 previously), but that's easily configured.

2023-07-12 18:30 UTC, wenhwang97 approved these changes

2023-07-12 18:31 UTC, merged